# Generated by Django 4.0.6 on 2025-08-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_testsession_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='test_type',
            field=models.CharField(choices=[('similar_count', 'عدد مواضع المتشابهات'), ('similar_on_pages', 'مواضع المتشابهات في الصفحات'), ('page_edges_quarters', 'بداية/نهاية الصفحات مع الأرباع'), ('order_juz_quarters', 'ترتيب الأجزاء والأرباع'), ('semantic_similarities', 'متشابهات معاني الآيات'), ('verse_location_quarters', 'موقع الآية في الربع والصفحة'), ('similar_only', 'Similar verses only'), ('similar_quarters', 'Similar verses & quarters'), ('similar_quarters_location', 'Similar verses & quarters with location'), ('mixed', 'Mixed')], default='similar_count', max_length=50),
        ),
    ]
