# Generated by Django 4.0.6 on 2025-09-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_testsession_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skin',
            field=models.CharField(default='default', help_text='Skin theme for the student', max_length=50),
        ),
    ]
