# Generated by Django 4.0.6 on 2025-09-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_skin'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='position_order',
            field=models.CharField(choices=[('normal', 'عادي'), ('reverse', 'عكسي')], default='normal', help_text='ترتيب المواضع في الأسئلة', max_length=20),
        ),
        migrations.AddField(
            model_name='testsession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='وقت بداية الاختبار', null=True),
        ),
    ]
