# Generated by Django 4.0.6 on 2025-09-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testsession_position_order_testsession_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phrase'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(default='similar_count', max_length=50),
        ),
    ]
