# Generated by Django 4.0.6 on 2025-09-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testquestion_correct_answer_testquestion_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
