# Generated by Django 4.0.6 on 2025-09-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_testquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='وقت الإجابة على السؤال', null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='وقت انتهاء الاختبار', null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='correct_answers',
            field=models.PositiveSmallIntegerField(blank=True, help_text='عدد الإجابات الصحيحة', null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='total_questions',
            field=models.PositiveSmallIntegerField(blank=True, help_text='إجمالي عدد الأسئلة', null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='unanswered',
            field=models.PositiveSmallIntegerField(blank=True, help_text='عدد الأسئلة غير المجاب عليها', null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='wrong_answers',
            field=models.PositiveSmallIntegerField(blank=True, help_text='عدد الإجابات الخاطئة', null=True),
        ),
    ]
