# Generated by Django 4.0.6 on 2025-09-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testquestion_answered_at_testsession_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='line',
            field=models.PositiveSmallIntegerField(blank=True, help_text='رقم السطر في الصفحة', null=True),
        ),
        migrations.AddField(
            model_name='ayah',
            name='text_imlaei',
            field=models.TextField(blank=True, help_text='النص الإملائي للآية'),
        ),
        migrations.AddField(
            model_name='ayah',
            name='text_uthmani',
            field=models.TextField(blank=True, help_text='النص العثماني للآية'),
        ),
    ]
