# Generated by Django 4.0.6 on 2025-09-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testquestion_answered_at_testsession_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ayah',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ayah',
            name='page',
        ),
        migrations.RemoveField(
            model_name='ayah',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='quarter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='juz',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='phrase',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='session',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='similarity_group',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='juzs',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='quarters',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='student',
        ),
    ]
