# Generated by Django 4.0.6 on 2025-09-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran_structure', '0001_initial'),
        ('core', '0011_alter_ayah_unique_together_remove_ayah_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraseoccurrence',
            name='ayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran_structure.ayah'),
        ),
        migrations.AlterField(
            model_name='similaritygroup',
            name='ayat',
            field=models.ManyToManyField(related_name='similarity_groups', to='quran_structure.ayah'),
        ),
        migrations.DeleteModel(
            name='Ayah',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Juz',
        ),
        migrations.DeleteModel(
            name='Quarter',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
    ]
