# Generated by Django 4.0.6 on 2025-09-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran_structure', '0001_initial'),
        ('students', '0001_initial'),
        ('core', '0011_alter_ayah_unique_together_remove_ayah_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='وقت بداية الاختبار', null=True)),
                ('test_type', models.CharField(choices=[('similar_count', 'عدد مواضع المتشابهات'), ('similar_on_pages', 'مواضع المتشابهات في الصفحات'), ('page_edges_quarters', 'بداية/نهاية الصفحات مع الأرباع'), ('order_juz_quarters', 'ترتيب الأجزاء والأرباع'), ('semantic_similarities', 'متشابهات معاني الآيات'), ('verse_location_quarters', 'موقع الآية في الربع والصفحة'), ('similar_only', 'Similar verses only'), ('similar_quarters', 'Similar verses & quarters'), ('similar_quarters_location', 'Similar verses & quarters with location'), ('mixed', 'Mixed')], default='similar_count', max_length=50)),
                ('num_questions', models.PositiveSmallIntegerField(default=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('position_order', models.CharField(choices=[('normal', 'عادي'), ('reverse', 'عكسي')], default='normal', help_text='ترتيب المواضع في الأسئلة', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='وقت انتهاء الاختبار', null=True)),
                ('total_questions', models.PositiveSmallIntegerField(blank=True, help_text='إجمالي عدد الأسئلة', null=True)),
                ('correct_answers', models.PositiveSmallIntegerField(blank=True, help_text='عدد الإجابات الصحيحة', null=True)),
                ('wrong_answers', models.PositiveSmallIntegerField(blank=True, help_text='عدد الإجابات الخاطئة', null=True)),
                ('unanswered', models.PositiveSmallIntegerField(blank=True, help_text='عدد الأسئلة غير المجاب عليها', null=True)),
                ('juzs', models.ManyToManyField(blank=True, to='quran_structure.juz')),
                ('quarters', models.ManyToManyField(blank=True, to='quran_structure.quarter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(default='similar_count', max_length=50)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('student_response', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, help_text='وقت الإجابة على السؤال', null=True)),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phrase')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.testsession')),
                ('similarity_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.similaritygroup')),
            ],
        ),
    ]
