# Generated by Django 4.0.6 on 2025-09-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_ayah_unique_together_remove_ayah_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_in_juz', models.PositiveSmallIntegerField(help_text='1–8 for each Juz')),
                ('label', models.CharField(help_text='Name of the quarter from the opening words of its first verse', max_length=100)),
                ('juz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran_structure.juz')),
            ],
            options={
                'unique_together': {('juz', 'index_in_juz')},
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.page')),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quran_structure.quarter')),
            ],
            options={
                'unique_together': {('surah', 'number')},
            },
        ),
    ]
