# Generated by Django 5.2.4 on 2025-08-02 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Juz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("image", models.ImageField(upload_to="pages/")),
            ],
        ),
        migrations.CreateModel(
            name="Quarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_in_juz",
                    models.PositiveSmallIntegerField(help_text="1–8 for each Juz"),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Name of the quarter from the opening words of its first verse",
                        max_length=100,
                    ),
                ),
                (
                    "juz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.juz"
                    ),
                ),
            ],
            options={
                "unique_together": {("juz", "index_in_juz")},
            },
        ),
        migrations.CreateModel(
            name="Ayah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surah", models.PositiveSmallIntegerField()),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.page",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.quarter",
                    ),
                ),
            ],
            options={
                "unique_together": {("surah", "number")},
            },
        ),
        migrations.CreateModel(
            name="SimilarityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Key phrase that identifies the group", max_length=200
                    ),
                ),
                (
                    "ayat",
                    models.ManyToManyField(
                        related_name="similarity_groups", to="core.ayah"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("similar_only", "Similar verses only"),
                            ("similar_quarters", "Similar verses & quarters"),
                            (
                                "similar_quarters_location",
                                "Similar verses & quarters with location",
                            ),
                            ("mixed", "Mixed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("num_questions", models.PositiveSmallIntegerField(default=10)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("juzs", models.ManyToManyField(blank=True, to="core.juz")),
                ("quarters", models.ManyToManyField(blank=True, to="core.quarter")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_response", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "similarity_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.similaritygroup",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.testsession",
                    ),
                ),
            ],
        ),
    ]
