# Generated by Django 4.0.6 on 2025-08-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('normalized', models.CharField(db_index=True, max_length=200)),
                ('length_words', models.PositiveSmallIntegerField()),
                ('global_freq', models.PositiveIntegerField(default=0)),
                ('confusability', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_word', models.PositiveSmallIntegerField()),
                ('end_word', models.PositiveSmallIntegerField()),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ayah')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.phrase')),
            ],
        ),
        migrations.AddIndex(
            model_name='phraseoccurrence',
            index=models.Index(fields=['ayah'], name='core_phrase_ayah_id_3090b4_idx'),
        ),
        migrations.AddIndex(
            model_name='phraseoccurrence',
            index=models.Index(fields=['phrase'], name='core_phrase_phrase__41b37c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='phraseoccurrence',
            unique_together={('phrase', 'ayah', 'start_word', 'end_word')},
        ),
    ]
