# Generated by Django 5.2.4 on 2025-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_student_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsession",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("similar_count", "عدد مواضع المتشابهات"),
                    ("similar_on_pages", "مواضع المتشابهات في الصفحات"),
                    ("page_edges_quarters", "بداية/نهاية الصفحات مع الأرباع"),
                    ("order_juz_quarters", "ترتيب الأجزاء والأرباع"),
                    ("semantic_similarities", "متشابهات معاني الآيات"),
                    ("similar_only", "Similar verses only"),
                    ("similar_quarters", "Similar verses & quarters"),
                    (
                        "similar_quarters_location",
                        "Similar verses & quarters with location",
                    ),
                    ("mixed", "Mixed"),
                ],
                default="similar_count",
                max_length=50,
            ),
        ),
    ]
